### PR TITLE
Added readme; Updated classes so that the wrapper doesn't cause an error if loaded twice.

### PR DESCRIPTION
**Pull request by ionutcalara**

### CODE REVIEW

**Review by tjconcept — COMMENTED** [review]
Seems like you missed the "Fetch card" in the index of the README?

The commits are a little bit messy, e.g. some refactorings with `class_exists` are in spread across both.

**Comment by tjconcept** [comment]
Looking good, ready to merge?

**Comment by ionutcalara** [comment]
I have added the missing item in the TOC, for the class_exists commit, in the commit that was after, its showing spacing related changes.

**Comment by ionutcalara** [comment]
Yes, i think so.  This is ready for merge.

**Pull request merged**
