### PR TITLE
Updated request structure to send objects via curl

### PR DESCRIPTION
**Pull request by ionutcalara**
Since we made changes to include create transaction which includes sending an object to the api, we need to make updates to the curl call to work in all php environments.

### CODE REVIEW

**Comment by tjconcept** [comment]
Looking good. Ready to merge?

**Comment by ionutcalara** [comment]
Yes, ready.

**Comment by tjconcept** [comment]
Please use rebasing when merging to keep a linear history.

**Comment by ionutcalara** [comment]
I did rebase the fork, should i squash the merge commit?

**Comment by tjconcept** [comment]
You should rebase the fork and do a fast forward merge. I guess you did the first but then merged with a merge commit.
Doing it from the GitHub UI it is the "rebase and merge" option.

**Pull request merged**
